apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: taiga-ingress
    annotations:
      kubernetes.io/ingress.class: {{.Values.ingress_class}}
      #ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/proxy-body-size: "100m"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - {{.Values.domain}}
    secretName: taiga-secret-tls
  rules:
  - host: {{.Values.domain}}
    http:
      paths:
      - path: /
        backend:
          serviceName: taiga-gateway
          servicePort: 80
