apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
stringData:
  password: {{.Values.postgres_pass | b64enc}}
---
apiVersion: v1
kind: Secret
metadata:
  name: taiga-key
type: Opaque
stringData:
  key: {{.Values.taiga_secret | b64enc}}
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
type: Opaque
stringData:
  password: {{.Values.rabbit_password | b64enc}}

---
apiVersion: v1
kind: Secret
metadata:
  name: email
type: Opaque
stringData:
  password: {{.Values.email_password | b64enc}}