apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.service_name}}-secrets
data:
{{if .Values.email}}
  mail_pass: {{.Values.sendgrid_token |b64enc }}
{{end}}
  vapid_priv_key: {{.Values.vapid_priv_key|b64enc}}
  vapid_pub_key: {{.Values.vapid_pub_key|b64enc}}
  minio_password: {{.Values.minio_password |b64enc}}
{{if .Values.voso_token}}
  voso_token: {{.Values.voso_token | b64enc}}
{{end}}