---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Values.service_name}}-mongodb
  labels:
    app: {{.Values.service_name}}-mongodb
spec:
  replicas: 1
  serviceName: {{.Values.service_name}}-mongodb
  selector:
    matchLabels:
      app: {{.Values.service_name}}-mongodb
  template:
    metadata:
      labels:
        app: {{.Values.service_name}}-mongodb
    spec:
      containers:
      - image: {{.Values.mongo_image}}
        name: mongodb
        volumeMounts:
          - mountPath: /data
            name: {{.Values.service_name}}-mongo-data
        resources:
          limits:
            memory: "2048Mi"
          requests:
            memory: "512Mi"
      volumes:
      - name: {{.Values.service_name}}-mongo-data
        persistentVolumeClaim:
          claimName: mongo-claim
      restartPolicy: Always