apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: {{.Values.service_name}}-ingress
    annotations:
      kubernetes.io/ingress.class: "nginx"
      ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/proxy-body-size: "100m"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - {{.Values.dns_entry}}
    secretName: {{.Values.service_name}}-secret-tls
  rules:
  - host: {{.Values.dns_entry}}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{.Values.service_name}}-service
          servicePort: 80
