---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.service_name}}-warden
  labels:
    app: {{.Values.service_name}}-warden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.service_name}}-warden
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 40%
  template:
    metadata:
      labels:
        app: {{.Values.service_name}}-warden
    spec:
      containers:
      - image: vaultwarden/server:latest
        env:
          - name: SIGNUPS_ALLOWED
            value: {{.Values.allow_signups | quote}}
          - name: IP_HEADER
            value: X-Forwarded-For
          {{if .Values.use_smtp}}
          - name: SMTP_HOST
            value: {{.Values.smtp_host | quote}}
          - name: SMTP_FROM
            value: {{.Values.smtp_from | quote}}
          - name: SMTP_PORT
            value: "587"
          - name: SMTP_SSL
            value: "true"
          - name: SMTP_USERNAME
            value: {{.Values.smtp_username | quote}}
          - name: SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.service_name }}-secrets
                key: mail_pass
          {{end}}
          - name: DOMAIN
            value: "https://{{.Values.dns_entry}}"
        name: vaultwarden
        volumeMounts:
          - mountPath: /data
            name: {{.Values.service_name}}-warden-data
        resources:
          limits:
            memory: "4096Mi"
          requests:
            memory: "1024Mi"
      volumes:
      - name: {{.Values.service_name}}-warden-data
        persistentVolumeClaim:
          claimName: warden-claim
      restartPolicy: Always
